baseURL = 'https://14maverick04.github.io/'
languageCode = 'en-us'
theme = 'anatole'
enableEmoji = true
enableRobotsTXT = true

[params]
author = 'Jerin Thomas'
contentratio = '0.80'
copyright = 'Jerin Thomas, 2020-{{ YEAR }}'
description = '"Tryst with Curiosity"'
doNotLoadAnimations = false
favicon = '/favicon/'
profilePicture = 'images/profile.jpg'
mainSections = [""]
customCss = ["css/styles.css"]
indexDateFormat = "2006-01-02"
singleDateFormat = "2006-01-02"
title = 'Jerin Thomas'


[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://linkedin.com/in/jerinthomas1404"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/jerinthomas1404"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:jerinthomas1498@gmail.com"


## Menu items
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Notables"
  identifier = "notes"
  weight = 200
  url = "/note"

  [[menu.main]]
  name = "About Me"
  identifier = "aboutme"
  weight = 300
  url = "/aboutme/resume/"

  [[menu.main]]
  name = "Tags"
  identifier = "tags"
  weight = 400
  url = "/tags/"


[taxonomies]
series = "series"
tag = "tags"